2025-06-25 00:29:03,404 ERROR Login failed. 'token' not found in response. Check credentials.
2025-06-25 00:29:17,386 ERROR Network error during login: HTTPSConnectionPool(host='api.pocketcasts.com', port=443): Max retries exceeded with url: /user/login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbbaff56630>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-06-25 00:29:17,388 ERROR Network error fetching history: HTTPSConnectionPool(host='api.pocketcasts.com', port=443): Max retries exceeded with url: /user/history (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbbaff56c90>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-06-25 00:29:26,838 ERROR Network error during login: HTTPSConnectionPool(host='api.pocketcasts.com', port=443): Max retries exceeded with url: /user/login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08af16d670>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-06-25 00:29:26,840 ERROR Network error fetching history: HTTPSConnectionPool(host='api.pocketcasts.com', port=443): Max retries exceeded with url: /user/history (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f08af16ed20>: Failed to establish a new connection: [Errno 111] Connection refused'))
